### ISSUE TITLE
InitialFeedback

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SmartShoppingCart#1]

**Comment by serviceproviderpk** [comment]
First of all read all points then  make changes in database, refresh edmx checkin code and DB then work on feedback.

1)  From  http://regularshare.com.ng/ copy the data of "Static Pages" in your local Database
2)  Move credit card images + logo to someother folder from "UploadedStuff"
3) Remove meta tags key from web.config
5) In "Categories" table add following fields (Photo,IsFeatured,NoOfViews int ,SNO int ,IsActive,IsDeleted as bit
6) From  Add/Edit Product page remove Color and Size TextBoxt and show "BriefDescription" textbox

pagetitle,pagekeywords should be below the "Description"textbox,  and Page should be multiline textbox instead of editor box.
also show "Brands" Dropdown when user want to add/edit any product.
7) In Product List page in admin section (/Dashboard/Product) in Grid show only Product Photo,title,prices only
 also add link of "Manage Color & Manage Size)
8) On product detail page,  show brief description below "QuickOverview" and description tab show description
9) In admin section  add link of "Manage Brands"
4) Add New table (CategoryColor[CategoryColorId,CategoryId,ColorText,ColorCode)
      Add New table (CategorySize[CategorySizeId,CategoryId,SizeText,SizeValue)
11)  Complete and test order flow as discussed
12) Email Notification 
a) Forgot password
b) Account Creation
c) Order Notification to Customer 
d) Order Notification to Supplier


13) On Home page these banners should be fetch from Database
![home page adds](https://cloud.githubusercontent.com/assets/19146254/25977868/19876476-36d8-11e7-9c4d-2695cbfb9692.PNG)
a) in product table add following fields
IsTrendy Bit,IsActive,IsDeleted and NoOfViews int
![image](https://cloud.githubusercontent.com/assets/19146254/25977903/5421efb6-36d8-11e7-8448-7501cf44fe41.png)
b) Add new table Banners(BannerId,BannerTitle,Description,Photo,Heading1,Heading2,Heading3,IsActive)

**Comment by WaqarShah** [comment]
1. From http://regularshare.com.ng/ copy the data of "Static Pages" in your local Database
                                                                                               **Fixed**
2. Move credit card images + logo to someother folder from "UploadedStuff"        **Fixed.**
Remove meta tags key from web.config                                   Pending
3. In "Categories" table add following fields (Photo,IsFeatured,NoOfViews int ,SNO int ,IsActive,IsDeleted as bit                                                                                   **Fixed.**
4. From Add/Edit Product page remove Color and Size TextBoxt and show "BriefDescription" textbox
pagetitle,pagekeywords should be below the "Description"textbox, and Page should be multiline textbox instead of editor box.                                                            
also show "Brands" Dropdown when user want to add/edit any product.           **Fixed**.
7) In Product List page in admin section (/Dashboard/Product) in Grid show only Product Photo,title,prices only                                                                                              **Fixed**.
also add link of "Manage Color & Manage Size)   **Pending**
8) On product detail page, show brief description below "QuickOverview" and description tab show description                                                                                                        **Fixed**.
9) In admin section add link of "Manage Brands"                                              **Fixed**.
4) Add New table (CategoryColor[CategoryColorId,CategoryId,ColorText,ColorCode)     **Fixed**.
Add New table (CategorySize[CategorySizeId,CategoryId,SizeText,SizeValue)                   **Fixed**.
11) Complete and test order flow as discussed                                  
                                                       **Fixed**.
12) Email Notification                    **Fixed**.
a) Forgot password                         **Fixed**.
b) Account Creation                       **Fixed.**
c) Order Notification to Customer                    **Fixed**.
d) Order Notification to Supplier                       **Fixed**.

13. On Home page these banners should be fetch from Database                 pending
a) in product table add following fields
IsTrendy Bit,IsActive,IsDeleted and NoOfViews int                                     **Fixed**.   
b) Add new table Banners(BannerId,BannerTitle,Description,Photo,Heading1,Heading2,Heading3,IsActive)
                                                                                                                    **Fixed**.

**Comment by WaqarShah** [comment]
1. From http://regularshare.com.ng/ copy the data of "Static Pages" in your local Database    **Fixed.**
2. Move credit card images + logo to someother folder from "UploadedStuff"                        **Fixed.**
3. Remove meta tags key from web.config                                                                                 **Pending.**
4. In "Categories" table add following fields (Photo,IsFeatured,NoOfViews int ,SNO int ,IsActive,IsDeleted as bit.                                                                                                                                              **Fixed.**
5. From Add/Edit Product page remove Color and Size TextBoxt and show "BriefDescription" textbox
pagetitle,pagekeywords should be below the "Description"textbox, and Page should be multiline textbox instead of editor box.
also show "Brands" Dropdown when user want to add/edit any product.                                    **Fixed.**

7) In Product List page in admin section (/Dashboard/Product) in Grid show only Product Photo,title,prices only       **Fixed.**
also add link of "Manage Color & Manage Size)             **Pending**
8) On product detail page, show brief description below "QuickOverview" and description tab show description                                                                   **Fixed.**
9) In admin section add link of "Manage Brands"          **Fixed.**
4) Add New table (CategoryColor[CategoryColorId,CategoryId,ColorText,ColorCode)             **Fixed.**
Add New table (CategorySize[CategorySizeId,CategoryId,SizeText,SizeValue)                            **Fixed.**
11) Complete and test order flow as discussed                        **Fixed.**
12) Email Notification                                                                **Fixed.**
a) Forgot password                                                                    **Fixed.**
b) Account Creation                                                                  **Fixed.**
c) Order Notification to Customer                                            **Fixed.**
d) Order Notification to Supplier                                              **Fixed.**


13. On Home page these banners should be fetch from Database    "90% Fixed, but need to be discussed"
a) in product table add following fields
IsTrendy Bit,IsActive,IsDeleted and NoOfViews int      **Fixed.**
image
b) Add new table Banners(BannerId,BannerTitle,Description,Photo,Heading1,Heading2,Heading3,IsActive) **Fixed.**

**Comment by WaqarShah** [comment]
0. Remove meta tags key from web.config.                               **Pending**.
1. In admin section Category list page Add "Manage Category Color,Manage Category Size)
2. In Product List page in admin section (/Dashboard/Product) in Grid also add link of "Manage Color & Manage Size)                                                                             **Pending**
3. On Home page these banners should be fetch from Database.    **90% Fixed, pending portion need to be discussed**
4.Add following New Tables
MenuSectionType(MenuSectionTypeId,Title,Description) 
MenuSections(MenuSectionId,MenuSectionTypeId,Title,Description,WebURL)
5. NoofViews field value will be set remove from UI

**Comment by WaqarShah** [comment]
Remove meta tags key from web.config.       **Fixed.**
In admin section Category list page Add "Manage Category Color,Manage Category Size)   **Fixed.**
In Product List page in admin section (/Dashboard/Product) in Grid also add link of "Manage Color & Manage Size)      Pending didn't understand fields
On Home page these banners should be fetch from Database. 90% Fixed, pending portion need to be discussed    
4.Add following New Tables
MenuSectionType(MenuSectionTypeId,Title,Description)  **Fixed.**
MenuSections(MenuSectionId,MenuSectionTypeId,Title,Description,WebURL)  **Fixed.**
NoofViews field value will be set remove from UI   **Fixed.**

**Comment by WaqarShah** [comment]
I notice all users have access to all order placed on the site, Users(buyers or suppliers) should only have access to their own order place or ad placed.           **Fixed.**
Free Shipping Nationwide Should be Change to Nationwide Low rate Shipping.  **Fixed**.

Please Change it to Below address

Address:
Regularshare.com.ng
Block C5 Success Plaza,Otunla B/Stop,Kajola Ibeju-Lekki Lagos Nigeria    **Fixed**.

Please change this email admin@regularshare.com to admin@regularshare.com.ng.  **Fixed.**
I see where you put Manage Colors and Sizes, but there is no link between Products and colors or sizes, there is no how someone can set colors or size when adding products     **Fixed some part pending.**

when buyers place an order, there should be a Link to the order so that we can easily identify which company the order is placed because there will be much company with the same order and same price at a time.           **Confusing**

when filing the form for order, I will like you to put an option where customers can easily click to choose if their billing address and shipping address are the same, if they are not the same then the person will enter the other info.     **Confusing.**

**Comment by serviceproviderpk** [comment]
- In Manage Products Add "Delete" icon when user will click on it, set its flag "IsDeleted=True" then it will be hided from system.
where you are getting list from db, add filter ( w=>w.IsDeleted=false)
when Product is Created set default values of folloiwng fields from backend

IsDeleted=false,IsActive=true,NoOfViews=0 and in edit product view also set Html.Hidden.. if any control is not used for them.
- From Order and Order Detail remove dummy entries and in orderDetail table add "SupplierID". and link it with usertable.
and also add relations. in order detail then show supplier name before product name.
- From Home page slider plz remove the text, that we added from DB.

- Product color/Size feature in working form.
- IF color or size is not added from any product then from Product Detail page hide color and Size options.
- in All Grids where we are showing prices in grid columns show currency symbol from web.config
- In  Dashobard footer remove brandostech and set compnay name from "web.config"

**Comment by WaqarShah** [comment]
From Order and Order Detail remove dummy entries and in orderDetail table add "SupplierID". and link it with usertable. and also add relations. in order detail then show supplier name before product name.    
                                                                                                                                            **Fixed.**
From Home page slider plz remove the text, that we added from DB.                               **Fixed.**

IF color or size is not added from any product then from Product Detail page hide color and Size options. 
                                                                                                                             **Fixed.**
in All Grids where we are showing prices in grid columns show currency symbol from web.config  
                                                                                                                             **Fixed.**
In Dashobard footer remove brandostech and set compnay name from "web.config".           **Fixed.**

**Comment by serviceproviderpk** [comment]
0- In Product Table add new field "ShipmentFee" Deciaml(18,2) and show him Crud of product
 when user place order also add "ShipmentFee"  like
(Price+Shipmentfee*Quanity)

1- When user logged  save his "First Name" as well as to show text below left photo in above the menu bar
2- When User is logged in show him only his "WishList"
3-  Supplier creation  &- Customer registeration dahsboard is not showing data according to user types
1.  There is Need for seller to set Shipping cost when adding" Products 

2.  so that when buyers place an order, before check-out, Shipping cost will be shown to the buyer and the total cost of items and shipping will be shown before clicking submit.

Shipping cost will be range from 500 Naira To 3000 Naira , Kindly fix this so that sellers will be able to set Shipping cost when adding products

3. when buyers place an order , there is a need for Notification to be sent to the Supplier, The admin and the Buyer.

4.I see all contacts under Customers, Suppliers and Buyers are the same, Customers were supposed to be under Customers and Buyers were Suppose to be under Buyers and Suppliers under Suppliers

5. I see there is only XXL and SM are under Sizes, there should be the following Sizes as well (S,M,L,XL,XXL).

**Comment by serviceproviderpk** [comment]
@**

> After completion TEST EAch page by entering proper data on local and server and dont forogt checkin code and status update on github

**

6- when supplier account is created send him email and cc admin
7-when customer account is send email to the customer and cc admin
**8- All statics pages data and title should be set from "DB" e.g;In About Us Section , I will like to Edit these Welcome to Smart Shopping Cart
Change it to Welcome to Regularshare Shop** .   **Fixed.**
**9- if admin set price and discount price same, on product detailpage price is 0**.    **Fixed.**
**10- in  Manage Product list page  "Action Icons" show in one row. delete icons should be last icon.** . . **Fixed.**
**11-  if Color and size is not mentioned for product, on product detail page, Hide label of "color" and "Size** 
 **and hide from "Shopping Cart" list page** .   **Fixed.**
**12- on /Account/NewCheckOut page   add check box " Same as above" Copy the above values in "Billing Information"
 and similary for "Shipping Information"**     **Fixed.**
 **b).  on right side bar  "Shopping Cart Items" Add currency, remove label "Image:"**  .  **Fixed.**

13- when customer place an order send emmail to customer and cc admin
**14- in all pages where price is displayed mension Currency Symbol.**     .      **Fixed.**
**15-  Admin should be able to see all orders list**                                   .     **Fixed.**
**16- Supplier should be able to see his order List.**                    .    **Fixed.**
17- when user is logged in he should be able to edit his profile all details instead of few columns
**18- in Edit Profile rename Email to "User Types" and dont show admin user type in dropdown list  .** **Fixed.**
**19- Admin should be able to Delete "Enquiry"**   **Fixed.**

**Comment by serviceproviderpk** [comment]
![image](https://cloud.githubusercontent.com/assets/19146254/26419833/5b07cb96-40da-11e7-8358-b64e40e857eb.png)

i m unable to change it  .

in banner add "Delete" option

**Comment by serviceproviderpk** [comment]
21. In Slide show   add "Delete" Option
**22. Contact us page all information should be change from web.config**
**23. When new product Get Action Render set bit value from backend lik
Model.IsTrend=false;
Model.IsFeature=falset etc**
24. In Crud of Static pages, "Page description should be textarea instead of "Editor box"

**Comment by serviceproviderpk** [comment]
Please work on issue according to the number, that you can not  do, Please bold it for discussion.
Instead of edit comments, Please add as new entry in github.


**I  have implemented same as above feature of jqury, I will explain in office just remind me.**
i have done for 1 textboxt do it for all plz

**Comment by WaqarShah** [comment]
Remaining tasks:
6- when supplier account is created send him email and cc admin .  **Fixed**
7-when customer account is send email to the customer and cc admin .   **Fixed**
13- when customer place an order send emmail to customer and cc admin.  **Fixed.**
22. Contact us page all information should be change from web.config. **Fixed.**
23. In static pages field add photo.  **Fixed.**
